version: "3.7"

services:
    rest:
        image: rest_rest
        ports:
            - 8000:3333
        logging:
            driver: "fluentd"
            options:
                fluentd-async-connect: "true"
                fluentd-address: localhost:24224
                tag: fluentd
